"""You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t."""

# I have manually given the input. This one works perfectly for other testcases too.

s="abcd"
t="abcde"
for i in t:
    if t.count(i)-s.count(i) is 1:
        return i